application: riskrisk-timerbot
version: 1
runtime: python
api_version: 1

handlers:

#- url: /(.*\.egg)
#  static_files: module/\1
#  upload: module/(.*\.egg)

- url: /run
  script: main.py

- url: /test
  script: main.py

- url: /default
  script: main.py

- url: /(.*\.html)
  static_files: static/\1
  upload: static/(.*\.html)

- url: /
  static_files: static/index.html
  upload: static/index.html

